"""Replacement vocabularies for the pseudonymiser.

Ordinary, public, common words — no real person's details are in this file. The
only property that matters for correctness is that each list is **stable**:
reordering one silently repseudonymises every log ever exported, so entries are
appended, never inserted or removed.
"""
from __future__ import annotations

#: 1408 entries
FIRST_NAMES = (
    "Aaliyah", "Aaron", "Abel", "Abigail", "Abner", "Abraham", "Ace", "Adair", "Adalynn",
    "Adam", "Ade", "Adelbert", "Adeline", "Adolfo", "Adrian", "Adriel", "Agustin", "Ahmad",
    "Aidan", "Aiden", "Aiko", "Ainsley", "Aisha", "Alan", "Alaric", "Alba", "Albert", "Alberto",
    "Alden", "Aldo", "Alec", "Alejandra", "Alejandro", "Alessandro", "Alessia", "Alexa",
    "Alexander", "Alexandra", "Alexis", "Alfonso", "Alfred", "Ali", "Alice", "Alina",
    "Alistair", "Allegra", "Allison", "Alma", "Alonzo", "Alphonse", "Alva", "Amadeo", "Amanda",
    "Amara", "Amber", "Ambrose", "Amelia", "Amias", "Amina", "Amos", "Amy", "Anahera", "Anais",
    "Anastasia", "Anders", "Andre", "Andrea", "Andrew", "Angel", "Angela", "Angharad", "Angus",
    "Anika", "Ann", "Anna", "Ansel", "Anselm", "Anthony", "Antoinette", "Antonio", "Aoife",
    "Apollo", "Araceli", "Arcadia", "Archer", "Ari", "Aria", "Ariana", "Arianna", "Ariel",
    "Arjun", "Armand", "Armani", "Arnav", "Arnold", "Aroha", "Arthur", "Arya", "Aryan", "Asa",
    "Asher", "Ashley", "Ashton", "Aspen", "Astra", "Astrid", "Athena", "Atlas", "Atticus",
    "Aubrey", "Audrey", "August", "Augustin", "Aurelia", "Aurelio", "Aurora", "Austin",
    "Autumn", "Ava", "Avery", "Axel", "Axton", "Ayden", "Ayla", "Azalea", "Azariah", "Bailey",
    "Balthazar", "Barbara", "Barnaby", "Baron", "Barrett", "Bartholomew", "Basil", "Baxter",
    "Bayard", "Beatrix", "Beau", "Beckett", "Bella", "Bellamy", "Benedict", "Benicio",
    "Benjamin", "Bennett", "Benoit", "Berenice", "Bernard", "Bertram", "Betty", "Beverly",
    "Bianca", "Billy", "Bjorn", "Blaine", "Blaise", "Blake", "Blythe", "Bo", "Bobby", "Bodhi",
    "Boniface", "Booker", "Boone", "Boris", "Bowen", "Braden", "Bradley", "Bram", "Brandon",
    "Brandt", "Brannon", "Brantley", "Braxton", "Brayden", "Brenda", "Brennan", "Brent",
    "Brett", "Brian", "Briar", "Brice", "Bridger", "Bridget", "Brielle", "Brigid", "Brittany",
    "Britton", "Brock", "Broderick", "Bronson", "Bronwen", "Brooklyn", "Brooks", "Bruce",
    "Bruno", "Bryan", "Bryce", "Brynn", "Bryson", "Buck", "Burke", "Byron", "Cade", "Cadence",
    "Caius", "Caleb", "Calla", "Callum", "Calvin", "Camden", "Cameron", "Camila", "Camille",
    "Campbell", "Candace", "Canyon", "Caoimhe", "Capri", "Cara", "Carina", "Carl", "Carlo",
    "Carmelo", "Carmen", "Carol", "Caroline", "Carolyn", "Carrick", "Carson", "Carter", "Carys",
    "Casimir", "Cassian", "Cassidy", "Castiel", "Catherine", "Cato", "Cecil", "Cecilia",
    "Cedar", "Celeste", "Celine", "Cesar", "Chandler", "Chandra", "Channing", "Chantal",
    "Chantelle", "Charity", "Charles", "Charlotte", "Charlton", "Chase", "Chen", "Cheryl",
    "Chesney", "Chester", "Chiara", "Chidi", "Chloe", "Christian", "Christina", "Christine",
    "Christopher", "Cian", "Cicely", "Cillian", "Claire", "Clara", "Clarence", "Clarissa",
    "Claude", "Claudia", "Clement", "Cleo", "Clifton", "Clive", "Clover", "Cody", "Colby",
    "Cole", "Colette", "Colin", "Collier", "Colm", "Colton", "Conan", "Conley", "Conner",
    "Conrad", "Constance", "Cooper", "Cora", "Corbin", "Cordelia", "Corinne", "Cormac",
    "Cornelius", "Cosima", "Coy", "Crispin", "Cruz", "Cullen", "Cynthia", "Cyril", "Cyrus",
    "Dahlia", "Dalia", "Dallas", "Dalton", "Damaris", "Damian", "Damon", "Dane", "Daniel",
    "Danielle", "Dante", "Daphne", "Darby", "Darcy", "Dario", "Darius", "Darla", "Darnell",
    "Darrell", "Daryl", "Dashiell", "David", "Davide", "Davina", "Dawn", "Dax", "Deacon",
    "Dean", "Deandre", "Deborah", "Debra", "Declan", "Dedric", "Deirdre", "Delaney", "Delia",
    "Delilah", "Dell", "Demetrius", "Denise", "Dennis", "Denver", "Derek", "Dermot", "Desmond",
    "Devon", "Dexter", "Diana", "Diane", "Dianne", "Diego", "Dieter", "Dimitri", "Dion",
    "Dixon", "Dmitri", "Dolores", "Dominic", "Dominique", "Donald", "Donna", "Donovan",
    "Dorian", "Doris", "Dorothea", "Dorothy", "Douglas", "Drake", "Drusilla", "Dudley",
    "Dustin", "Dwight", "Dylan", "Eamon", "Earl", "Eartha", "Easton", "Eben", "Edgar", "Edith",
    "Edmund", "Edna", "Edward", "Edwin", "Egan", "Eileen", "Eira", "Elaine", "Elara", "Elden",
    "Eldon", "Eleanor", "Elena", "Eleni", "Eli", "Eliana", "Elias", "Elijah", "Elio", "Eliot",
    "Elise", "Elizabeth", "Ella", "Ellery", "Ellie", "Elliot", "Elodie", "Eloise", "Elroy",
    "Elsa", "Elsie", "Elton", "Elvira", "Elwood", "Emeric", "Emerson", "Emery", "Emil",
    "Emilia", "Emilio", "Emily", "Emma", "Emmanuel", "Emmeline", "Emmett", "Emrys", "Enid",
    "Ennis", "Enzo", "Ephraim", "Erasmus", "Eric", "Erica", "Erik", "Erin", "Ernest", "Errol",
    "Esme", "Esperanza", "Estelle", "Esther", "Ethan", "Etienne", "Etta", "Eudora", "Eugene",
    "Eugenia", "Eulalia", "Eunice", "Euphemia", "Eustace", "Eva", "Evan", "Evander",
    "Evangeline", "Evelyn", "Everard", "Everett", "Everly", "Ewan", "Ezekiel", "Ezio", "Ezra",
    "Fabian", "Faith", "Fallon", "Farrah", "Fatima", "Faye", "Federico", "Felicity", "Felix",
    "Fenton", "Ferdinand", "Fergal", "Fergus", "Fidel", "Finlay", "Finn", "Finnegan", "Fiona",
    "Fitzgerald", "Fletcher", "Fleur", "Flint", "Flora", "Florence", "Floyd", "Forrest",
    "Fortune", "Foster", "Frances", "Francesca", "Francis", "Frank", "Franklin", "Frederick",
    "Freya", "Fulton", "Gabriel", "Gabriella", "Gaia", "Galen", "Gareth", "Garrett", "Garrick",
    "Gary", "Gavin", "Gemma", "Genesis", "Genevieve", "Geoffrey", "George", "Georgia",
    "Georgina", "Gerald", "Geraldine", "Gerard", "Gianna", "Gideon", "Gilbert", "Giles",
    "Gillian", "Gina", "Giovanni", "Giselle", "Giulia", "Glen", "Glenda", "Gloria", "Godfrey",
    "Golda", "Gordon", "Grace", "Grady", "Graeme", "Granger", "Grayson", "Gregor", "Gregory",
    "Greta", "Greyson", "Griffin", "Griselda", "Guinevere", "Gunnar", "Gustav", "Guthrie",
    "Gwen", "Gwendolyn", "Hadley", "Hadrian", "Hailey", "Haley", "Halle", "Hamish", "Hana",
    "Haneul", "Hannah", "Harlan", "Harlow", "Harmony", "Harold", "Harper", "Harriet", "Harvey",
    "Hassan", "Haven", "Hayden", "Hazel", "Heath", "Heather", "Hector", "Hedwig", "Heidi",
    "Helen", "Helena", "Helga", "Hendrix", "Henry", "Herbert", "Hermione", "Hester", "Hilda",
    "Hillary", "Hiram", "Hiro", "Holden", "Honor", "Horace", "Hortense", "Hosea", "Howell",
    "Hoyt", "Hubert", "Hudson", "Hugo", "Humphrey", "Hunter", "Hyacinth", "Ian", "Ibrahim",
    "Ida", "Idris", "Ifor", "Ignatius", "Ilana", "Ilona", "Ilse", "Imani", "Imelda", "Imogen",
    "India", "Indigo", "Ines", "Inga", "Ingram", "Ingrid", "Iona", "Irene", "Irina", "Iris",
    "Irving", "Isaac", "Isabella", "Isabelle", "Isadora", "Isaiah", "Isaias", "Isidore", "Isla",
    "Ismael", "Isolde", "Ivan", "Iver", "Ivor", "Ivy", "Jabari", "Jace", "Jacinta", "Jacinto",
    "Jack", "Jacob", "Jacqueline", "Jada", "Jade", "Jaime", "Jamal", "James", "Jameson",
    "Jamila", "Janelle", "Janet", "Janice", "Jarrett", "Jarvis", "Jasmine", "Jason", "Jasper",
    "Javier", "Jax", "Jaxon", "Jaxson", "Jaya", "Jayden", "Jean", "Jedidiah", "Jeffrey",
    "Jemima", "Jenna", "Jennifer", "Jensen", "Jeremiah", "Jeremy", "Jericho", "Jerome", "Jerry",
    "Jesse", "Jessica", "Jethro", "Jillian", "Jing", "Jiwoo", "Joan", "Joanna", "Joaquin",
    "Jocelyn", "Joe", "Johanna", "John", "Jolene", "Jonah", "Jonas", "Jonathan", "Joni",
    "Jordan", "Jorge", "Jose", "Josef", "Joseph", "Josephine", "Joshua", "Josiah", "Joslyn",
    "Jovan", "Joyce", "Juan", "Juanita", "Jubilee", "Judah", "Jude", "Judith", "Judy", "Julia",
    "Julian", "Juliana", "Julie", "Juliet", "Juniper", "Juno", "Justin", "Justine", "Kai",
    "Kaia", "Kalani", "Kaleb", "Kamila", "Kane", "Kara", "Kareem", "Karen", "Karina", "Karl",
    "Karma", "Karter", "Kasper", "Kassandra", "Katherine", "Kathleen", "Kathryn", "Katya",
    "Kaya", "Kayden", "Kayla", "Kaylee", "Keaton", "Keegan", "Keira", "Keith", "Kelly",
    "Kelsey", "Kendra", "Kenji", "Kenna", "Kennedy", "Kenneth", "Kensington", "Kerry", "Kevin",
    "Keziah", "Kian", "Kiera", "Killian", "Kimberly", "Kingston", "Kinsley", "Kiran", "Kirby",
    "Kirsten", "Klara", "Klaus", "Knox", "Kofi", "Kora", "Kurt", "Kyle", "Kylie", "Kyra",
    "Lachlan", "Laila", "Laird", "Lamar", "Lambert", "Lance", "Landon", "Landry", "Langston",
    "Lara", "Larkin", "Larry", "Lars", "Laszlo", "Latham", "Laura", "Laurel", "Lauren",
    "Laurent", "Lavinia", "Lawrence", "Lawson", "Layla", "Layth", "Lazarus", "Leah", "Leander",
    "Leandra", "Leif", "Leighton", "Leila", "Leilani", "Leland", "Lena", "Lennon", "Lennox",
    "Leo", "Leona", "Leonardo", "Leonie", "Leopold", "Lerato", "Leroy", "Lesley", "Lester",
    "Letitia", "Levi", "Lewis", "Lexi", "Liam", "Liana", "Liliana", "Lilith", "Lillian", "Lily",
    "Lincoln", "Linda", "Lindsay", "Ling", "Linnea", "Linus", "Lionel", "Lisa", "Lisbeth",
    "Livia", "Llewellyn", "Logan", "Lorcan", "Lorelei", "Lorenzo", "Loretta", "Lori", "Lorna",
    "Lorraine", "Lottie", "Louisa", "Lourdes", "Lowell", "Luc", "Lucas", "Lucia", "Lucian",
    "Lucille", "Lucy", "Ludmila", "Ludwig", "Luella", "Luka", "Luke", "Lumen", "Luna", "Luther",
    "Lydia", "Lyla", "Lyle", "Lyndon", "Lyra", "Mabel", "Macey", "Mackenzie", "Maddox",
    "Madeleine", "Madeline", "Madelyn", "Madison", "Maeve", "Magdalena", "Maggie", "Magnus",
    "Maisie", "Malachi", "Malcolm", "Malik", "Mallory", "Manon", "Manuel", "Mara", "Marcel",
    "Marcella", "Marco", "Marcus", "Margaret", "Margery", "Margot", "Maria", "Mariah",
    "Marianne", "Marie", "Marigold", "Marilyn", "Marina", "Mario", "Mariska", "Marius", "Mark",
    "Marlon", "Marlowe", "Marnie", "Marsha", "Martha", "Martina", "Marvin", "Mary", "Maryam",
    "Mason", "Mateo", "Mathias", "Matilda", "Matteo", "Matthew", "Maureen", "Maurice",
    "Maverick", "Mavis", "Maxine", "Maxwell", "Maya", "Mccoy", "Meara", "Megan", "Mei",
    "Melanie", "Melissa", "Meredith", "Merrick", "Mervyn", "Micaela", "Micah", "Michael",
    "Michelle", "Mikhail", "Milan", "Mildred", "Miles", "Miller", "Milo", "Minjun", "Mira",
    "Mirabel", "Miranda", "Miriam", "Mitchell", "Moana", "Mohsin", "Moira", "Monique",
    "Montgomery", "Morgana", "Morrison", "Mortimer", "Moses", "Muriel", "Murray", "Mustafa",
    "Myra", "Myron", "Nadia", "Nadine", "Nala", "Nancy", "Naomi", "Napoleon", "Nash", "Nasir",
    "Natalia", "Natalie", "Natasha", "Nathan", "Nathanael", "Nathaniel", "Nayeli", "Neal",
    "Nell", "Nelson", "Nerissa", "Nerys", "Nessa", "Nevaeh", "Nevin", "Newton", "Ngozi", "Nia",
    "Niamh", "Nicholas", "Nicole", "Nicolette", "Nigel", "Nikita", "Nikolai", "Nikolas", "Nils",
    "Nina", "Noah", "Noel", "Noelle", "Nolan", "Nora", "Norah", "Norbert", "Norma", "Norman",
    "Norton", "Nova", "Nyla", "Oakley", "Obadiah", "Octavia", "Odessa", "Odile", "Odin",
    "Ofelia", "Olaf", "Oleander", "Olga", "Olive", "Oliver", "Olivia", "Omar", "Ondine", "Opal",
    "Ophelia", "Orion", "Orla", "Orson", "Osborne", "Oscar", "Osgood", "Osiris", "Oswald",
    "Otis", "Ottilie", "Otto", "Ovid", "Owain", "Owen", "Pablo", "Padraig", "Paisley", "Paloma",
    "Pamela", "Pandora", "Paola", "Parker", "Pascal", "Patience", "Patrice", "Patricia",
    "Patrick", "Paul", "Paxton", "Pearl", "Pedro", "Penelope", "Percival", "Peregrine", "Perry",
    "Peter", "Petra", "Peyton", "Phaedra", "Philip", "Phoebe", "Phoenix", "Pierce", "Pierre",
    "Pilar", "Piper", "Portia", "Prescott", "Preston", "Primrose", "Priscilla", "Priya",
    "Prosper", "Prudence", "Quentin", "Quillon", "Quincy", "Quinlan", "Quinn", "Rachel",
    "Raelynn", "Rafael", "Rafferty", "Raina", "Ralph", "Ramona", "Randall", "Randy", "Rangi",
    "Ransom", "Raphael", "Raquel", "Raul", "Raven", "Ravi", "Raymond", "Reagan", "Rebecca",
    "Reeve", "Regina", "Reginald", "Reid", "Remington", "Remy", "Renata", "Rene", "Reuben",
    "Rex", "Rhea", "Rhett", "Rhiannon", "Rhoda", "Rhodes", "Rhys", "Ricardo", "Riccardo",
    "Richard", "Rider", "Rigby", "Riley", "Riordan", "Roan", "Robert", "Robin", "Rocco",
    "Roderick", "Rodrigo", "Roger", "Rohan", "Roisin", "Rolando", "Rollo", "Roman", "Romilly",
    "Ronald", "Ronan", "Roosevelt", "Rory", "Rosalie", "Rosalind", "Roscoe", "Rose", "Rosemary",
    "Roslyn", "Rowan", "Rowena", "Roxana", "Roy", "Royce", "Ruby", "Rufus", "Rupert", "Rurik",
    "Russell", "Ruth", "Rutherford", "Ryan", "Ryder", "Ryker", "Ryland", "Rylee", "Sabine",
    "Sabrina", "Sacha", "Sadie", "Saffron", "Sage", "Saira", "Salome", "Salvador", "Samantha",
    "Samara", "Samuel", "Sandra", "Sanjay", "Santana", "Santiago", "Saoirse", "Sapphire",
    "Sara", "Sarah", "Sasha", "Saul", "Savannah", "Sawyer", "Saxon", "Scarlet", "Scarlett",
    "Scott", "Seamus", "Sean", "Sebastian", "Seoyeon", "Seraphina", "Seren", "Serenity",
    "Sergei", "Sergio", "Seth", "Seymour", "Shane", "Shannon", "Sharon", "Shauna", "Shelby",
    "Sheldon", "Sherman", "Shiloh", "Shirley", "Sidney", "Sienna", "Sigmund", "Sigrid", "Silas",
    "Simon", "Simone", "Sinclair", "Sinead", "Siobhan", "Sipho", "Skylar", "Skyler", "Sloane",
    "Sofia", "Solomon", "Sonia", "Sophia", "Sophie", "Sora", "Soren", "Sorrel", "Spencer",
    "Stanley", "Stella", "Stellan", "Stephanie", "Stephen", "Sterling", "Steven", "Stuart",
    "Sullivan", "Susan", "Susanna", "Sutton", "Svetlana", "Sybil", "Sylvester", "Sylvie",
    "Tabitha", "Talia", "Tallulah", "Tamara", "Tamsin", "Tane", "Tanner", "Tansy", "Tara",
    "Tarquin", "Tatiana", "Tatum", "Tavish", "Taylor", "Teagan", "Temperance", "Tennyson",
    "Teresa", "Terrence", "Terry", "Tessa", "Thabo", "Thaddeus", "Thalia", "Thea", "Thelma",
    "Theodora", "Theodore", "Theresa", "Theron", "Thomas", "Thurston", "Tiberius", "Tierney",
    "Tilda", "Timothy", "Tobias", "Tomas", "Torin", "Tovah", "Tremaine", "Trevor", "Trinity",
    "Tristan", "Truman", "Trystan", "Tulip", "Turner", "Tyler", "Tyson", "Ulysses", "Una",
    "Ursula", "Vada", "Valentina", "Valeria", "Valerie", "Vance", "Vanessa", "Vaughn", "Veda",
    "Verity", "Verona", "Veronica", "Vesper", "Vicente", "Victor", "Victoria", "Vida", "Vienna",
    "Vincent", "Vincenzo", "Viola", "Violet", "Virgil", "Virginia", "Vivian", "Vivienne",
    "Vladimir", "Wade", "Waldo", "Wallace", "Walter", "Wanda", "Warner", "Warwick", "Watson",
    "Waverly", "Waylon", "Wayne", "Wei", "Wendell", "Wendy", "Wesley", "Weston", "Whitaker",
    "Whitney", "Wilbur", "Wilda", "Wilfred", "Wilhelmina", "Willa", "William", "Willie",
    "Willow", "Winifred", "Winston", "Wolfgang", "Wren", "Wyatt", "Xander", "Xanthe", "Xavier",
    "Xena", "Ximena", "Yael", "Yara", "Yasmin", "Yolanda", "Yuki", "Yusuf", "Yves", "Yvette",
    "Yvonne", "Zachary", "Zadie", "Zander", "Zara", "Zebulon", "Zelda", "Zephyr", "Zoey",
    "Zora", "Zuri",
)

#: 234 entries
LAST_NAMES = (
    "Adams", "Aguilar", "Alexander", "Allen", "Alvarado", "Alvarez", "Anderson", "Andrews",
    "Armstrong", "Arnold", "Bailey", "Baker", "Barnes", "Bell", "Bennett", "Berry", "Black",
    "Boyd", "Bradley", "Brooks", "Brown", "Bryant", "Burns", "Butler", "Campbell", "Carpenter",
    "Carroll", "Carter", "Castillo", "Castro", "Chavez", "Chen", "Clark", "Cole", "Coleman",
    "Collins", "Contreras", "Cook", "Cooper", "Cox", "Crawford", "Cruz", "Cunningham",
    "Daniels", "Davis", "Delgado", "Diaz", "Dixon", "Duncan", "Dunn", "Edwards", "Elliott",
    "Ellis", "Evans", "Ferguson", "Fernandez", "Fisher", "Flores", "Ford", "Foster", "Fox",
    "Freeman", "Garcia", "Gardner", "Garza", "Gibson", "Gomez", "Gonzales", "Gonzalez",
    "Gordon", "Graham", "Grant", "Gray", "Green", "Griffin", "Guerrero", "Gutierrez", "Guzman",
    "Hall", "Hamilton", "Hansen", "Harris", "Harrison", "Hart", "Hawkins", "Hayes", "Henderson",
    "Henry", "Hernandez", "Herrera", "Hicks", "Hill", "Hoffman", "Holmes", "Howard", "Hudson",
    "Hughes", "Hunt", "Hunter", "Jackson", "James", "Jenkins", "Jimenez", "Johnson", "Johnston",
    "Jones", "Jordan", "Kelley", "Kelly", "Kennedy", "Kim", "King", "Knight", "Lane",
    "Lawrence", "Lee", "Lewis", "Long", "Lopez", "Marshall", "Martin", "Martinez", "Mason",
    "Matthews", "Mcdonald", "Medina", "Mendez", "Mendoza", "Meyer", "Miller", "Mills",
    "Mitchell", "Moore", "Morales", "Moreno", "Morgan", "Morris", "Munoz", "Murphy", "Murray",
    "Myers", "Nelson", "Nguyen", "Nichols", "Olson", "Ortiz", "Owens", "Palmer", "Parker",
    "Patel", "Patterson", "Payne", "Pena", "Perez", "Perkins", "Perry", "Peters", "Peterson",
    "Phillips", "Pierce", "Porter", "Powell", "Price", "Ramirez", "Ramos", "Ray", "Reed",
    "Reyes", "Reynolds", "Rice", "Richards", "Richardson", "Riley", "Rivera", "Roberts",
    "Robertson", "Robinson", "Rodriguez", "Rogers", "Romero", "Rose", "Ross", "Ruiz", "Russell",
    "Ryan", "Salazar", "Sanchez", "Sanders", "Sandoval", "Santos", "Schmidt", "Scott", "Shaw",
    "Silva", "Simmons", "Simpson", "Smith", "Snyder", "Soto", "Spencer", "Stephens", "Stevens",
    "Stewart", "Stone", "Sullivan", "Taylor", "Thomas", "Thompson", "Torres", "Tran", "Tucker",
    "Turner", "Vargas", "Vasquez", "Vazquez", "Wagner", "Walker", "Wallace", "Ward", "Warren",
    "Washington", "Watson", "Weaver", "Webb", "Wells", "West", "White", "Williams", "Willis",
    "Wilson", "Wood", "Woods", "Wright", "Young",
)

#: 631 entries
NICKNAMES = (
    "Abby", "Ace", "Addie", "Adie", "Al", "Alex", "Alfie", "Ally", "Ambi", "Andi", "Andy",
    "Angel", "Angie", "Annie", "Archie", "Arlo", "Artie", "Ash", "Aud", "Bailey", "Bams",
    "Barb", "Bash", "Baz", "Bea", "Becca", "Becky", "Bee", "Bella", "Ben", "Benny", "Bert",
    "Bess", "Beth", "Betsy", "Bev", "Bex", "Biff", "Bill", "Billy", "Birdie", "Bix", "Blaze",
    "Bo", "Bob", "Bobbie", "Bobby", "Bonnie", "Boo", "Brad", "Bram", "Brandy", "Bree", "Brick",
    "Brie", "Brin", "Bron", "Bubba", "Bud", "Buddy", "Bug", "Bunny", "Cade", "Cal", "Cally",
    "Cam", "Cara", "Carrie", "Cass", "Cassie", "Cat", "Cathy", "Cece", "Chad", "Char",
    "Charlie", "Chas", "Chaz", "Cher", "Chick", "Chico", "Chip", "Chris", "Chrissy", "Chuck",
    "Cindy", "Cissy", "Clay", "Clem", "Cleo", "Cliff", "Coco", "Cody", "Col", "Cole", "Con",
    "Connie", "Coop", "Cory", "Craig", "Cricket", "Curt", "Cy", "Dai", "Daisy", "Dale", "Dan",
    "Danny", "Dash", "Dave", "Davey", "Deb", "Debbie", "Dee", "Deedee", "Del", "Dell", "Dennie",
    "Dex", "Dick", "Didi", "Dill", "Dixie", "Dizzy", "Dob", "Doc", "Dodge", "Dodie", "Dolf",
    "Dolly", "Don", "Donnie", "Dot", "Dottie", "Doug", "Dov", "Drew", "Drex", "Duke", "Dutch",
    "Eck", "Ed", "Eddie", "Edie", "Edo", "Effie", "Ella", "Elle", "Ellie", "Elm", "Els", "Ely",
    "Em", "Emmet", "Emmy", "Ernie", "Ethel", "Eve", "Ezra", "Fabe", "Fay", "Fen", "Fern", "Fi",
    "Fifi", "Finn", "Fitz", "Fizz", "Flash", "Fletch", "Flip", "Flo", "Fran", "Frank",
    "Frankie", "Freck", "Fred", "Freddy", "Frey", "Fritz", "Gabby", "Gabe", "Gail", "Gav",
    "Gem", "Gene", "Gerry", "Gib", "Gigi", "Gil", "Gill", "Ginny", "Gio", "Gordy", "Grady",
    "Gray", "Greer", "Gret", "Griff", "Gunn", "Gus", "Gwen", "Hab", "Hadi", "Hail", "Hal",
    "Hank", "Hap", "Harls", "Harry", "Hattie", "Hazel", "Hen", "Hep", "Herb", "Hero", "Hettie",
    "Hetty", "Hollie", "Hollis", "Honey", "Hoot", "Hop", "Hope", "Hugh", "Hux", "Ida", "Ike",
    "Indie", "Ines", "Ira", "Isa", "Ivy", "Izz", "Izzy", "Jack", "Jackie", "Jake", "Jan",
    "Jane", "Janie", "Jax", "Jay", "Jed", "Jeff", "Jem", "Jen", "Jenny", "Jer", "Jerry", "Jess",
    "Jessie", "Jet", "Jill", "Jim", "Jimmy", "Jinx", "Jo", "Jock", "Jodie", "Joe", "Joey",
    "Johnny", "Jon", "Jools", "Josh", "Josie", "Joy", "Jude", "Judy", "Jules", "Julie", "Junie",
    "Kade", "Kai", "Kass", "Kat", "Kate", "Katie", "Kay", "Kaz", "Keeks", "Kel", "Ken", "Kenny",
    "Kes", "Kez", "Kiki", "Kim", "Kip", "Kit", "Kitty", "Knox", "Kody", "Kris", "Kyle", "Lacey",
    "Lacy", "Lana", "Lark", "Larry", "Lash", "Laurie", "Laz", "Lee", "Len", "Lenny", "Leo",
    "Les", "Lex", "Libby", "Libs", "Lil", "Link", "Lish", "Liz", "Lizzie", "Lois", "Lola",
    "Lolo", "Lon", "Lonnie", "Loo", "Lorn", "Lott", "Lou", "Lucky", "Lucy", "Lud", "Luka",
    "Lulu", "Lux", "Lyn", "Mac", "Mack", "Maddie", "Madge", "Mads", "Mae", "Maggie", "Maisie",
    "Mandy", "Manny", "Marge", "Marty", "Marv", "Matt", "Mattie", "Maud", "Mave", "Max",
    "Maxie", "Maz", "Meg", "Mel", "Merry", "Mick", "Midge", "Miff", "Miggy", "Mike", "Millie",
    "Milt", "Mimi", "Mindy", "Minnie", "Mitch", "Mitzi", "Mo", "Moe", "Mole", "Molly", "Mona",
    "Monty", "Morrie", "Mort", "Moss", "Muff", "Murph", "Nab", "Nan", "Nancy", "Nat", "Nate",
    "Ned", "Nell", "Nellie", "Nemo", "Nev", "Newt", "Nib", "Nick", "Nicky", "Nico", "Nina",
    "Nip", "Nita", "Noel", "Noll", "Nonny", "Nora", "Norm", "Nub", "Nug", "Odie", "Ollie",
    "Onyx", "Ope", "Orly", "Oz", "Ozzy", "Pace", "Paddy", "Pam", "Pat", "Patsy", "Patty",
    "Paul", "Paulie", "Pax", "Pea", "Peach", "Peg", "Peggy", "Pem", "Pen", "Penny", "Pep",
    "Pete", "Pez", "Phil", "Phin", "Pia", "Pico", "Pim", "Pip", "Pixie", "Plum", "Podge", "Pol",
    "Polly", "Pooch", "Pop", "Posy", "Prim", "Prue", "Pud", "Quill", "Quin", "Quinn", "Rae",
    "Raff", "Rags", "Ralph", "Ram", "Randy", "Rax", "Ray", "Reba", "Red", "Reef", "Reg", "Remy",
    "Rex", "Rho", "Rib", "Rich", "Rick", "Ricky", "Rif", "Rig", "Rilla", "Rip", "Rita", "Rob",
    "Robbie", "Robby", "Rock", "Rod", "Roddy", "Rolo", "Ron", "Ronnie", "Roo", "Rook", "Rory",
    "Rosie", "Rox", "Roz", "Rube", "Rudy", "Rue", "Ruff", "Russ", "Rusty", "Ruthie", "Sable",
    "Sacha", "Sadie", "Sal", "Sally", "Sam", "Sammy", "Sandy", "Sara", "Sass", "Sax", "Scoot",
    "Scout", "Seb", "Sena", "Shep", "Sib", "Sid", "Sim", "Sis", "Skeet", "Skip", "Sky", "Slim",
    "Smitty", "Snap", "Sonny", "Spike", "Sprout", "Squid", "Stace", "Stan", "Stell", "Steve",
    "Stevie", "Stew", "Sue", "Sunny", "Susie", "Suzy", "Sy", "Syd", "Tab", "Tad", "Taff", "Tam",
    "Tammy", "Tank", "Tate", "Tavi", "Tay", "Ted", "Teddy", "Terri", "Terry", "Tess", "Tex",
    "Thad", "Theo", "Thom", "Tibby", "Tick", "Tilly", "Tim", "Timmy", "Tina", "Tip", "Titus",
    "Toby", "Todd", "Toff", "Tolly", "Tom", "Tommy", "Toni", "Tonk", "Tony", "Topper", "Tori",
    "Trace", "Tracy", "Trap", "Trey", "Trish", "Trix", "Trudy", "Tuck", "Tug", "Twig", "Ty",
    "Val", "Vale", "Van", "Vee", "Vera", "Vern", "Vess", "Vic", "Vicky", "Vin", "Vinnie", "Viv",
    "Vonn", "Wags", "Wally", "Walt", "Wanda", "Web", "Wen", "Wes", "Whit", "Wick", "Wig",
    "Wilf", "Will", "Willie", "Win", "Winn", "Winnie", "Wisp", "Wolf", "Woody", "Wren", "Wyn",
    "Yancy", "Yaz", "Zach", "Zeb", "Zed", "Zeke", "Zen", "Zip", "Zoe", "Zola", "Zub",
)

#: 124 entries
STREET_NAMES = (
    "Abbey", "Adams", "Alder", "Anvil", "Ash", "Aspen", "Beech", "Bell", "Bethel", "Birch",
    "Bracken", "Bramble", "Bridge", "Brook", "Calvary", "Cedar", "Chapel", "Chestnut", "Church",
    "Clover", "Comfrey", "Creek", "Crossing", "Cypress", "East", "Elm", "Fairview", "Fennel",
    "Ferry", "Field", "Fir", "Forge", "Foundry", "Foxglove", "Franklin", "Garden", "Grace",
    "Grand", "Greenway", "Grove", "Hamilton", "Harbour", "Harvest", "Hawthorn", "Hazel",
    "Heather", "Heritage", "Hickory", "Highland", "Hill", "Hillcrest", "Holly", "Independence",
    "Jackson", "Jefferson", "Junction", "Juniper", "Kennedy", "Kiln", "Lake", "Lakeview",
    "Larch", "Laurel", "Liberty", "Lincoln", "Linden", "Lower", "Lowland", "Madison",
    "Magnolia", "Maple", "Market", "Meadow", "Mill", "Mission", "Monroe", "Myrtle", "New",
    "North", "Oak", "Old", "Olive", "Orchard", "Parish", "Parkway", "Pine", "Pioneer", "Poplar",
    "Prairie", "Primrose", "Priory", "Quarry", "Ridge", "River", "Riverside", "Roosevelt",
    "Rowan", "Settler", "Shepherd", "Sorrel", "South", "Spring", "Spruce", "Station", "Summit",
    "Sunrise", "Sunset", "Sycamore", "Tansy", "Thistle", "Trinity", "Truman", "Union", "Upper",
    "Valley", "Vervain", "Walnut", "West", "Wharf", "Willow", "Wilson", "Woodland", "Yarrow",
    "Zion",
)

#: 14 entries
STREET_TYPES = (
    "Avenue", "Boulevard", "Close", "Court", "Crescent", "Drive", "Lane", "Place", "Road",
    "Row", "Street", "Terrace", "Walk", "Way",
)

#: 100 entries
CITIES = (
    "Arlington", "Ashland", "Auburn", "Bedford", "Belmont", "Berkeley", "Bridgewater",
    "Bristol", "Brookfield", "Burlington", "Cambridge", "Canton", "Carlisle", "Chester",
    "Clayton", "Clinton", "Concord", "Cranford", "Danbury", "Dayton", "Dover", "Dunmore",
    "Easton", "Elmwood", "Fairfield", "Fairmont", "Fairview", "Franklin", "Georgetown",
    "Glenwood", "Greenville", "Hanover", "Harrington", "Hartland", "Haverford", "Hillsboro",
    "Hudson", "Ipswich", "Jamestown", "Kendall", "Kingston", "Lakewood", "Lancaster", "Langley",
    "Larkspur", "Lebanon", "Lexington", "Madison", "Manchester", "Maplewood", "Marion",
    "Medford", "Middleton", "Milton", "Montrose", "Newport", "Norwood", "Oakland", "Oxford",
    "Pemberton", "Pinehurst", "Plainview", "Princeton", "Ravenna", "Redland", "Richmond",
    "Ridgefield", "Riverton", "Rochester", "Rockport", "Rosedale", "Salem", "Saybrook",
    "Seabrook", "Shelburne", "Sheridan", "Somerset", "Southport", "Springfield", "Stanton",
    "Sterling", "Stonebridge", "Sunderland", "Thornbury", "Torrington", "Trenton", "Vernon",
    "Wakefield", "Warren", "Waverly", "Wellington", "Westbrook", "Weston", "Wheaton",
    "Whitfield", "Winchester", "Woodbridge", "Wrenfield", "Yarmouth", "Yorktown",
)

#: 50 entries
STATES = (
    "AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN",
    "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH",
    "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA",
    "VT", "WA", "WI", "WV", "WY",
)

#: 11 entries
EMAIL_DOMAINS = (
    "example.com", "example.net", "example.org", "inbox.example", "letters.example",
    "mail.example", "mailbox.example", "post.example", "relay.example", "send.example",
    "webmail.example",
)
